FROM node:lts as build-stage
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY . /app/
RUN npm run build -- --outputPath=./dist/out

FROM nginx:alpine
COPY --from=build-stage /app/dist/out/ /usr/share/nginx/html
EXPOSE 80

